-- ============================================================
-- 废水排放调度系统 - 数据库建表脚本
-- 数据库版本：Oracle 11g Enterprise Edition Release 11.2.0.1.0
-- 创建日期  ：2026-04-10
-- 更新日期  ：2026-04-13
-- 对应文档  ：TDD_废水排放调度系统 v1.2 / PRD_废水排放调度系统 v1.5
-- 说明      ：全部语法兼容 Oracle 11g，不使用 FETCH FIRST / IDENTITY 等 12c+ 特性
-- ============================================================


-- ============================================================
-- PART 1：序列（Sequences）
-- ============================================================

-- 储罐状态表主键序列
CREATE SEQUENCE SEQ_TANK_STATUS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 调度结果表主键序列
CREATE SEQUENCE SEQ_SCHEDULE_RESULT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 告警记录表主键序列
CREATE SEQUENCE SEQ_ALERT_LOG
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 调度输入快照表主键序列
CREATE SEQUENCE SEQ_SCHEDULE_INPUT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 调度输入车间快照表主键序列
CREATE SEQUENCE SEQ_SCHEDULE_INPUT_WORKSHOP
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


-- ============================================================
-- PART 2：建表（Tables）
-- ============================================================

-- ------------------------------------------------------------
-- 表1：车间基础信息表 WW_WORKSHOP_INFO
-- ------------------------------------------------------------
CREATE TABLE WW_WORKSHOP_INFO (
    WORKSHOP_ID         VARCHAR2(20)    NOT NULL,
    WORKSHOP_NAME       VARCHAR2(100)   NOT NULL,
    MAX_DISCHARGE_RATE  NUMBER(10, 4)   NOT NULL,   -- 最大排放速率（m³/h）
    MIN_DISCHARGE_RATE  NUMBER(10, 4)   NOT NULL,   -- 最小排放速率（m³/h），管道最低流量要求
    PRIORITY_WEIGHT     NUMBER(6, 4)    NOT NULL,   -- 优先级权重（默认 1.0，值越大优先级越高）
    IS_ACTIVE           NUMBER(1)       NOT NULL,   -- 是否启用（1:是 0:否）
    REMARK              VARCHAR2(500),
    CREATE_TIME         TIMESTAMP       NOT NULL,
    UPDATE_TIME         TIMESTAMP       NOT NULL,
    CONSTRAINT PK_WW_WORKSHOP_INFO    PRIMARY KEY (WORKSHOP_ID),
    CONSTRAINT CHK_WORKSHOP_IS_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT CHK_WORKSHOP_MAX_RATE CHECK (MAX_DISCHARGE_RATE > 0),
    CONSTRAINT CHK_WORKSHOP_MIN_RATE CHECK (MIN_DISCHARGE_RATE >= 0),
    CONSTRAINT CHK_WORKSHOP_WEIGHT CHECK (PRIORITY_WEIGHT > 0),
    CONSTRAINT CHK_WORKSHOP_RATE_ORD CHECK (MAX_DISCHARGE_RATE >= MIN_DISCHARGE_RATE)
);

COMMENT ON TABLE  WW_WORKSHOP_INFO                    IS '车间基础信息表';
COMMENT ON COLUMN WW_WORKSHOP_INFO.WORKSHOP_ID        IS '车间编号，主键';
COMMENT ON COLUMN WW_WORKSHOP_INFO.WORKSHOP_NAME      IS '车间名称';
COMMENT ON COLUMN WW_WORKSHOP_INFO.MAX_DISCHARGE_RATE IS '最大排放速率（m³/h）';
COMMENT ON COLUMN WW_WORKSHOP_INFO.MIN_DISCHARGE_RATE IS '最小排放速率（m³/h），管道最低流量要求';
COMMENT ON COLUMN WW_WORKSHOP_INFO.PRIORITY_WEIGHT    IS '优先级权重（默认1.0，值越大优先级越高）';
COMMENT ON COLUMN WW_WORKSHOP_INFO.IS_ACTIVE          IS '是否启用（1:是 0:否）';
COMMENT ON COLUMN WW_WORKSHOP_INFO.REMARK             IS '备注';
COMMENT ON COLUMN WW_WORKSHOP_INFO.CREATE_TIME        IS '创建时间';
COMMENT ON COLUMN WW_WORKSHOP_INFO.UPDATE_TIME        IS '最后更新时间';


-- ------------------------------------------------------------
-- 表2：系统参数配置表 WW_SYSTEM_CONFIG
-- ------------------------------------------------------------
CREATE TABLE WW_SYSTEM_CONFIG (
    CONFIG_KEY      VARCHAR2(100)   NOT NULL,
    CONFIG_VALUE    VARCHAR2(500)   NOT NULL,
    CONFIG_DESC     VARCHAR2(500),
    UPDATE_TIME     TIMESTAMP       NOT NULL,
    CONSTRAINT PK_WW_SYSTEM_CONFIG PRIMARY KEY (CONFIG_KEY)
);

COMMENT ON TABLE  WW_SYSTEM_CONFIG             IS '系统参数配置表';
COMMENT ON COLUMN WW_SYSTEM_CONFIG.CONFIG_KEY   IS '配置项键名，主键';
COMMENT ON COLUMN WW_SYSTEM_CONFIG.CONFIG_VALUE IS '配置项值';
COMMENT ON COLUMN WW_SYSTEM_CONFIG.CONFIG_DESC  IS '配置项说明';
COMMENT ON COLUMN WW_SYSTEM_CONFIG.UPDATE_TIME  IS '最后更新时间';


-- ------------------------------------------------------------
-- 表3：储罐状态表 WW_TANK_STATUS
-- ------------------------------------------------------------
CREATE TABLE WW_TANK_STATUS (
    STATUS_ID       NUMBER(20)      NOT NULL,
    RECORD_TIME     TIMESTAMP       NOT NULL,
    CURRENT_LEVEL   NUMBER(10, 4)   NOT NULL,   -- 当前液位（m³）
    LEVEL_RATIO     NUMBER(6, 4)    NOT NULL,   -- 液位占比（= 当前液位 / 储罐容量）
    TANK_STATUS     VARCHAR2(20)    NOT NULL,   -- NORMAL / WARNING / ALERT / EMERGENCY
    PREDICTED_LEVEL NUMBER(10, 4),              -- 下周期预测液位（m³），可为空
    INPUT_TYPE      VARCHAR2(20)    NOT NULL,   -- MANUAL / AUTO
    INPUT_BY        VARCHAR2(100),              -- 录入人，自动采集时可为空
    CREATE_TIME     TIMESTAMP       NOT NULL,
    CONSTRAINT PK_WW_TANK_STATUS        PRIMARY KEY (STATUS_ID)
);

COMMENT ON TABLE  WW_TANK_STATUS                 IS '储罐状态表';
COMMENT ON COLUMN WW_TANK_STATUS.STATUS_ID        IS '主键，由序列 SEQ_TANK_STATUS 自增';
COMMENT ON COLUMN WW_TANK_STATUS.RECORD_TIME      IS '记录时间';
COMMENT ON COLUMN WW_TANK_STATUS.CURRENT_LEVEL    IS '当前液位（m³）';
COMMENT ON COLUMN WW_TANK_STATUS.LEVEL_RATIO      IS '液位占比（= 当前液位 / 储罐容量）';
COMMENT ON COLUMN WW_TANK_STATUS.TANK_STATUS      IS '液位状态（NORMAL/WARNING/ALERT/EMERGENCY）';
COMMENT ON COLUMN WW_TANK_STATUS.PREDICTED_LEVEL  IS '下周期预测液位（m³），告警/紧急区间时为 L - C×T';
COMMENT ON COLUMN WW_TANK_STATUS.INPUT_TYPE       IS '录入方式（MANUAL:人工 / AUTO:传感器，预留）';
COMMENT ON COLUMN WW_TANK_STATUS.INPUT_BY         IS '录入人（自动采集时为空）';
COMMENT ON COLUMN WW_TANK_STATUS.CREATE_TIME      IS '记录创建时间';


-- ------------------------------------------------------------
-- 表4：调度结果表 WW_SCHEDULE_RESULT
-- ------------------------------------------------------------
CREATE TABLE WW_SCHEDULE_RESULT (
    RESULT_ID           NUMBER(20)      NOT NULL,
    SCHEDULE_ID         VARCHAR2(50)    NOT NULL,   -- 调度批次号（UUID），同一次调度各车间相同
    SCHEDULE_TIME       TIMESTAMP       NOT NULL,   -- 调度执行时间
    WORKSHOP_ID         VARCHAR2(20)    NOT NULL,   -- 车间编号
    ALLOWED_RATE        NUMBER(10, 4)   NOT NULL,   -- 建议排放速率（m³/h），即决策变量 r_i
    ALLOWED_VOLUME      NUMBER(10, 4)   NOT NULL,   -- 推算排放量（m³）= ALLOWED_RATE × T
    TANK_LEVEL_BEFORE   NUMBER(10, 4)   NOT NULL,   -- 调度前液位（m³）
    SCHEDULE_STATUS     VARCHAR2(20)    NOT NULL,   -- NORMAL / WARNING / ALERT / EMERGENCY
    SOLVER_STATUS       VARCHAR2(50)    NOT NULL,   -- Optimal / Infeasible / SKIPPED / Timeout
    CREATE_TIME         TIMESTAMP       NOT NULL,
    CONSTRAINT PK_WW_SCHEDULE_RESULT    PRIMARY KEY (RESULT_ID)
);

COMMENT ON TABLE  WW_SCHEDULE_RESULT                   IS '调度结果表（建议值，不具备控制指令属性）';
COMMENT ON COLUMN WW_SCHEDULE_RESULT.RESULT_ID          IS '主键，由序列 SEQ_SCHEDULE_RESULT 自增';
COMMENT ON COLUMN WW_SCHEDULE_RESULT.SCHEDULE_ID        IS '调度批次号（UUID），同一次调度所有车间共享';
COMMENT ON COLUMN WW_SCHEDULE_RESULT.SCHEDULE_TIME      IS '调度执行时间';
COMMENT ON COLUMN WW_SCHEDULE_RESULT.WORKSHOP_ID        IS '车间编号，关联 WW_WORKSHOP_INFO';
COMMENT ON COLUMN WW_SCHEDULE_RESULT.ALLOWED_RATE       IS '本周期建议排放速率（m³/h），即决策变量 r_i';
COMMENT ON COLUMN WW_SCHEDULE_RESULT.ALLOWED_VOLUME     IS '本周期推算排放量（m³）= ALLOWED_RATE × T';
COMMENT ON COLUMN WW_SCHEDULE_RESULT.TANK_LEVEL_BEFORE  IS '调度前储罐液位（m³）';
COMMENT ON COLUMN WW_SCHEDULE_RESULT.SCHEDULE_STATUS    IS '调度状态（NORMAL/WARNING/ALERT/EMERGENCY）';
COMMENT ON COLUMN WW_SCHEDULE_RESULT.SOLVER_STATUS      IS '求解器状态（Optimal/Infeasible/SKIPPED/Timeout）';
COMMENT ON COLUMN WW_SCHEDULE_RESULT.CREATE_TIME        IS '记录创建时间';


-- ------------------------------------------------------------
-- 表5：告警记录表 WW_ALERT_LOG
-- ------------------------------------------------------------
CREATE TABLE WW_ALERT_LOG (
    ALERT_ID        NUMBER(20)      NOT NULL,
    SCHEDULE_ID     VARCHAR2(50),               -- 调度批次号，关联 WW_SCHEDULE_RESULT
    ALERT_TIME      TIMESTAMP       NOT NULL,
    ALERT_LEVEL     NUMBER(1)       NOT NULL,   -- 2:告警 3:紧急
    TANK_LEVEL      NUMBER(10, 4)   NOT NULL,   -- 告警时液位（m³）
    LEVEL_RATIO     NUMBER(6, 4)    NOT NULL,   -- 告警时液位占比
    ALERT_MESSAGE   VARCHAR2(500)   NOT NULL,   -- 告警描述
    IS_HANDLED      NUMBER(1)       NOT NULL,   -- 是否已处理（1:是 0:否）
    HANDLED_BY      VARCHAR2(100),
    HANDLED_TIME    TIMESTAMP,
    HANDLE_REMARK   VARCHAR2(500),
    CREATE_TIME     TIMESTAMP       NOT NULL,
    CONSTRAINT PK_WW_ALERT_LOG          PRIMARY KEY (ALERT_ID)
);

COMMENT ON TABLE  WW_ALERT_LOG               IS '告警记录表';
COMMENT ON COLUMN WW_ALERT_LOG.ALERT_ID       IS '主键，由序列 SEQ_ALERT_LOG 自增';
COMMENT ON COLUMN WW_ALERT_LOG.SCHEDULE_ID    IS '调度批次号，关联 WW_SCHEDULE_RESULT';
COMMENT ON COLUMN WW_ALERT_LOG.ALERT_TIME     IS '告警时间';
COMMENT ON COLUMN WW_ALERT_LOG.ALERT_LEVEL    IS '告警级别（2:告警 3:紧急）';
COMMENT ON COLUMN WW_ALERT_LOG.TANK_LEVEL     IS '告警时液位（m³）';
COMMENT ON COLUMN WW_ALERT_LOG.LEVEL_RATIO    IS '告警时液位占比';
COMMENT ON COLUMN WW_ALERT_LOG.ALERT_MESSAGE  IS '告警描述';
COMMENT ON COLUMN WW_ALERT_LOG.IS_HANDLED     IS '是否已处理（1:是 0:否）';
COMMENT ON COLUMN WW_ALERT_LOG.HANDLED_BY     IS '处理人';
COMMENT ON COLUMN WW_ALERT_LOG.HANDLED_TIME   IS '处理时间';
COMMENT ON COLUMN WW_ALERT_LOG.HANDLE_REMARK  IS '处理备注';
COMMENT ON COLUMN WW_ALERT_LOG.CREATE_TIME    IS '记录创建时间';


-- ------------------------------------------------------------
-- 表6：调度输入快照表 WW_SCHEDULE_INPUT
-- 存储每次调度运行时的系统级配置快照，便于复盘、调试和AI训练
-- ------------------------------------------------------------
CREATE TABLE WW_SCHEDULE_INPUT (
    INPUT_ID                NUMBER(20)      NOT NULL,
    SCHEDULE_ID             VARCHAR2(50)    NOT NULL,   -- 调度批次号，关联 WW_SCHEDULE_RESULT
    SCHEDULE_TIME           TIMESTAMP       NOT NULL,   -- 调度执行时间
    TANK_CAPACITY           NUMBER(10, 4)   NOT NULL,   -- 储罐容量 V（m³）
    PROCESS_CAPACITY        NUMBER(10, 4)   NOT NULL,   -- 处理总能力 C（m³/h）
    SCHEDULE_INTERVAL_MIN   NUMBER(10)      NOT NULL,   -- 调度周期（分钟）
    SAFE_RATIO              NUMBER(6, 4)    NOT NULL,   -- 安全容量系数
    WARNING_RATIO           NUMBER(6, 4)    NOT NULL,   -- 预警阈值
    ALERT_RATIO             NUMBER(6, 4)    NOT NULL,   -- 告警阈值
    EMERGENCY_RATIO         NUMBER(6, 4)    NOT NULL,   -- 紧急阈值
    MIN_RATE_RATIO          NUMBER(6, 4)    NOT NULL,   -- 弹性压缩最低保留比例
    PROCESS_BUFFER_RATIO    NUMBER(6, 4)    NOT NULL,   -- 处理能力缓冲系数
    TANK_LEVEL              NUMBER(10, 4)   NOT NULL,   -- 调度时储罐液位（m³）
    LEVEL_RATIO             NUMBER(6, 4)    NOT NULL,   -- 调度时液位占比
    ZONE                    VARCHAR2(20)    NOT NULL,   -- 液位区间（NORMAL/WARNING/ALERT/EMERGENCY）
    ELASTIC_K               NUMBER(6, 4),               -- 弹性系数 k（预警区间有效）
    CAPACITY_LIMIT          NUMBER(10, 4),              -- 容量约束上限计算值（m³/h）
    PROCESS_LIMIT           NUMBER(10, 4),              -- 处理能力约束上限计算值（m³/h）
    EFFECTIVE_LIMIT         NUMBER(10, 4),              -- 实际生效约束上限
    WORKSHOP_COUNT          NUMBER(5)       NOT NULL,   -- 本次调度启用车间数量
    CREATE_TIME             TIMESTAMP       NOT NULL,
    CONSTRAINT PK_WW_SCHEDULE_INPUT    PRIMARY KEY (INPUT_ID)
);

COMMENT ON TABLE  WW_SCHEDULE_INPUT                    IS '调度输入快照表（系统级配置）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.INPUT_ID           IS '主键，由序列 SEQ_SCHEDULE_INPUT 自增';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.SCHEDULE_ID        IS '调度批次号，关联 WW_SCHEDULE_RESULT';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.SCHEDULE_TIME      IS '调度执行时间';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.TANK_CAPACITY      IS '储罐容量 V（m³）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.PROCESS_CAPACITY   IS '处理总能力 C（m³/h）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.SCHEDULE_INTERVAL_MIN IS '调度周期（分钟）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.SAFE_RATIO         IS '安全容量系数';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.WARNING_RATIO      IS '预警阈值';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.ALERT_RATIO        IS '告警阈值';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.EMERGENCY_RATIO    IS '紧急阈值';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.MIN_RATE_RATIO     IS '弹性压缩最低保留比例';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.PROCESS_BUFFER_RATIO IS '处理能力缓冲系数';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.TANK_LEVEL         IS '调度时储罐液位（m³）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.LEVEL_RATIO        IS '调度时液位占比';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.ZONE               IS '液位区间（NORMAL/WARNING/ALERT/EMERGENCY）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.ELASTIC_K          IS '弹性系数 k（预警区间有效，其他为NULL）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.CAPACITY_LIMIT     IS '容量约束上限计算值（m³/h）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.PROCESS_LIMIT      IS '处理能力约束上限计算值（m³/h）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.EFFECTIVE_LIMIT    IS '实际生效约束上限（min(capacity, process)）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.WORKSHOP_COUNT     IS '本次调度启用车间数量';
COMMENT ON COLUMN WW_SCHEDULE_INPUT.CREATE_TIME        IS '记录创建时间';


-- ------------------------------------------------------------
-- 表7：调度输入车间快照表 WW_SCHEDULE_INPUT_WORKSHOP
-- 存储每次调度运行时各车间的配置快照
-- ------------------------------------------------------------
CREATE TABLE WW_SCHEDULE_INPUT_WORKSHOP (
    INPUT_WORKSHOP_ID   NUMBER(20)      NOT NULL,
    SCHEDULE_ID         VARCHAR2(50)    NOT NULL,   -- 调度批次号，关联 WW_SCHEDULE_INPUT
    WORKSHOP_ID         VARCHAR2(20)    NOT NULL,   -- 车间编号
    WORKSHOP_NAME       VARCHAR2(100)   NOT NULL,   -- 车间名称
    MAX_DISCHARGE_RATE  NUMBER(10, 4)   NOT NULL,   -- 最大排放速率（m³/h）
    MIN_DISCHARGE_RATE  NUMBER(10, 4)   NOT NULL,   -- 最小排放速率（m³/h）
    PRIORITY_WEIGHT     NUMBER(6, 4)    NOT NULL,   -- 优先级权重
    ELASTIC_MAX_RATE    NUMBER(10, 4),              -- 弹性压缩后的速率上限（m³/h）
    CREATE_TIME         TIMESTAMP       NOT NULL,
    CONSTRAINT PK_WW_SCHEDULE_INPUT_WORKSHOP PRIMARY KEY (INPUT_WORKSHOP_ID)
);

COMMENT ON TABLE  WW_SCHEDULE_INPUT_WORKSHOP                   IS '调度输入车间快照表';
COMMENT ON COLUMN WW_SCHEDULE_INPUT_WORKSHOP.INPUT_WORKSHOP_ID IS '主键，由序列 SEQ_SCHEDULE_INPUT_WORKSHOP 自增';
COMMENT ON COLUMN WW_SCHEDULE_INPUT_WORKSHOP.SCHEDULE_ID       IS '调度批次号，关联 WW_SCHEDULE_INPUT';
COMMENT ON COLUMN WW_SCHEDULE_INPUT_WORKSHOP.WORKSHOP_ID       IS '车间编号';
COMMENT ON COLUMN WW_SCHEDULE_INPUT_WORKSHOP.WORKSHOP_NAME     IS '车间名称';
COMMENT ON COLUMN WW_SCHEDULE_INPUT_WORKSHOP.MAX_DISCHARGE_RATE IS '最大排放速率（m³/h）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT_WORKSHOP.MIN_DISCHARGE_RATE IS '最小排放速率（m³/h）';
COMMENT ON COLUMN WW_SCHEDULE_INPUT_WORKSHOP.PRIORITY_WEIGHT   IS '优先级权重';
COMMENT ON COLUMN WW_SCHEDULE_INPUT_WORKSHOP.ELASTIC_MAX_RATE  IS '弹性压缩后的速率上限（m³/h），预警区间有效';
COMMENT ON COLUMN WW_SCHEDULE_INPUT_WORKSHOP.CREATE_TIME       IS '记录创建时间';


-- ============================================================
-- PART 3：索引（Indexes）
-- ============================================================

-- WW_WORKSHOP_INFO：按启用状态过滤
CREATE INDEX IDX_WORKSHOP_IS_ACTIVE
    ON WW_WORKSHOP_INFO (IS_ACTIVE);

-- WW_TANK_STATUS：读最新人工录入液位的核心查询路径
CREATE INDEX IDX_TANK_INPUT_CREATE
    ON WW_TANK_STATUS (INPUT_TYPE, CREATE_TIME);

-- WW_TANK_STATUS：按液位状态查询
CREATE INDEX IDX_TANK_STATUS_VAL
    ON WW_TANK_STATUS (TANK_STATUS);

-- WW_SCHEDULE_RESULT：按调度批次聚合查询
CREATE INDEX IDX_SCHEDULE_BATCH
    ON WW_SCHEDULE_RESULT (SCHEDULE_ID);

-- WW_SCHEDULE_RESULT：按时间范围查询历史记录
CREATE INDEX IDX_SCHEDULE_TIME
    ON WW_SCHEDULE_RESULT (SCHEDULE_TIME);

-- WW_SCHEDULE_RESULT：按车间查询调度历史
CREATE INDEX IDX_SCHEDULE_WORKSHOP
    ON WW_SCHEDULE_RESULT (WORKSHOP_ID);

-- WW_ALERT_LOG：查询未处理告警
CREATE INDEX IDX_ALERT_IS_HANDLED
    ON WW_ALERT_LOG (IS_HANDLED);

-- WW_ALERT_LOG：按告警级别过滤
CREATE INDEX IDX_ALERT_LEVEL
    ON WW_ALERT_LOG (ALERT_LEVEL);

-- WW_ALERT_LOG：按时间范围查询
CREATE INDEX IDX_ALERT_TIME
    ON WW_ALERT_LOG (ALERT_TIME);

-- WW_ALERT_LOG：按调度批次号查询
CREATE INDEX IDX_ALERT_SCHEDULE_ID
    ON WW_ALERT_LOG (SCHEDULE_ID);

-- WW_SCHEDULE_INPUT：按调度批次号查询
CREATE INDEX IDX_SCHEDULE_INPUT_ID
    ON WW_SCHEDULE_INPUT (SCHEDULE_ID);

-- WW_SCHEDULE_INPUT：按时间范围查询历史快照
CREATE INDEX IDX_SCHEDULE_INPUT_TIME
    ON WW_SCHEDULE_INPUT (SCHEDULE_TIME);

-- WW_SCHEDULE_INPUT_WORKSHOP：按调度批次号查询
CREATE INDEX IDX_INPUT_WORKSHOP_SCHEDULE
    ON WW_SCHEDULE_INPUT_WORKSHOP (SCHEDULE_ID);

-- WW_SCHEDULE_INPUT_WORKSHOP：按车间查询历史快照
CREATE INDEX IDX_INPUT_WORKSHOP_WS
    ON WW_SCHEDULE_INPUT_WORKSHOP (WORKSHOP_ID);


-- ============================================================
-- PART 4：初始数据（Initial Data）
-- ============================================================

-- ------------------------------------------------------------
-- 4.1 系统参数配置初始化（WW_SYSTEM_CONFIG）
-- 参数值来源：PRD_废水排放调度系统 v1.4 §5.2
-- ------------------------------------------------------------
INSERT INTO WW_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, UPDATE_TIME)
VALUES ('TANK_CAPACITY', '500',
        '储罐容量（m³），即变量 V', SYSTIMESTAMP);

INSERT INTO WW_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, UPDATE_TIME)
VALUES ('PROCESS_CAPACITY', '60',
        '总处理能力（m³/h），即变量 C', SYSTIMESTAMP);

INSERT INTO WW_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, UPDATE_TIME)
VALUES ('SCHEDULE_INTERVAL_MIN', '30',
        '调度周期（分钟），即变量 T = 此值 / 60 小时', SYSTIMESTAMP);

INSERT INTO WW_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, UPDATE_TIME)
VALUES ('SAFE_RATIO', '0.85',
        '安全容量系数，调度后预测液位不超过 TANK_CAPACITY × SAFE_RATIO', SYSTIMESTAMP);

INSERT INTO WW_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, UPDATE_TIME)
VALUES ('WARNING_RATIO', '0.80',
        '预警阈值，液位超过 TANK_CAPACITY × WARNING_RATIO 时触发弹性速率压缩', SYSTIMESTAMP);

INSERT INTO WW_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, UPDATE_TIME)
VALUES ('ALERT_RATIO', '0.90',
        '告警阈值，液位超过 TANK_CAPACITY × ALERT_RATIO 时生成停排建议（高优先级）', SYSTIMESTAMP);

INSERT INTO WW_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, UPDATE_TIME)
VALUES ('EMERGENCY_RATIO', '0.95',
        '紧急阈值，液位超过 TANK_CAPACITY × EMERGENCY_RATIO 时生成紧急停排建议', SYSTIMESTAMP);

INSERT INTO WW_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, UPDATE_TIME)
VALUES ('MIN_RATE_RATIO', '0.30',
        '弹性压缩最低保留比例（预警末端最低保留此比例的排放速率）；设为0时末端速率线性降至0', SYSTIMESTAMP);

INSERT INTO WW_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, UPDATE_TIME)
VALUES ('PROCESS_BUFFER_RATIO', '1.20',
        '处理能力缓冲系数，总排放速率上限 = PROCESS_CAPACITY × PROCESS_BUFFER_RATIO', SYSTIMESTAMP);

INSERT INTO WW_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, UPDATE_TIME)
VALUES ('MANUAL_LEVEL_STALE_THRESHOLD', '2',
        '液位数据超期阈值（调度周期倍数），超过此倍数的液位数据视为超期', SYSTIMESTAMP);


-- ------------------------------------------------------------
-- 4.2 车间初始数据（WW_WORKSHOP_INFO）
-- MVP 阶段 7 个车间，最大排放速率 12 m³/h，最小排放速率 2 m³/h，权重统一 1.0
-- 参数值来源：PRD §4.6 调度示例
-- ------------------------------------------------------------
INSERT INTO WW_WORKSHOP_INFO
    (WORKSHOP_ID, WORKSHOP_NAME, MAX_DISCHARGE_RATE, MIN_DISCHARGE_RATE,
     PRIORITY_WEIGHT, IS_ACTIVE, REMARK, CREATE_TIME, UPDATE_TIME)
VALUES ('WS001', '车间1', 12, 2, 1.0, 1, 'MVP阶段统一预设参数，后续可差异化配置', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO WW_WORKSHOP_INFO
    (WORKSHOP_ID, WORKSHOP_NAME, MAX_DISCHARGE_RATE, MIN_DISCHARGE_RATE,
     PRIORITY_WEIGHT, IS_ACTIVE, REMARK, CREATE_TIME, UPDATE_TIME)
VALUES ('WS002', '车间2', 12, 2, 1.0, 1, 'MVP阶段统一预设参数，后续可差异化配置', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO WW_WORKSHOP_INFO
    (WORKSHOP_ID, WORKSHOP_NAME, MAX_DISCHARGE_RATE, MIN_DISCHARGE_RATE,
     PRIORITY_WEIGHT, IS_ACTIVE, REMARK, CREATE_TIME, UPDATE_TIME)
VALUES ('WS003', '车间3', 12, 2, 1.0, 1, 'MVP阶段统一预设参数，后续可差异化配置', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO WW_WORKSHOP_INFO
    (WORKSHOP_ID, WORKSHOP_NAME, MAX_DISCHARGE_RATE, MIN_DISCHARGE_RATE,
     PRIORITY_WEIGHT, IS_ACTIVE, REMARK, CREATE_TIME, UPDATE_TIME)
VALUES ('WS004', '车间4', 12, 2, 1.0, 1, 'MVP阶段统一预设参数，后续可差异化配置', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO WW_WORKSHOP_INFO
    (WORKSHOP_ID, WORKSHOP_NAME, MAX_DISCHARGE_RATE, MIN_DISCHARGE_RATE,
     PRIORITY_WEIGHT, IS_ACTIVE, REMARK, CREATE_TIME, UPDATE_TIME)
VALUES ('WS005', '车间5', 12, 2, 1.0, 1, 'MVP阶段统一预设参数，后续可差异化配置', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO WW_WORKSHOP_INFO
    (WORKSHOP_ID, WORKSHOP_NAME, MAX_DISCHARGE_RATE, MIN_DISCHARGE_RATE,
     PRIORITY_WEIGHT, IS_ACTIVE, REMARK, CREATE_TIME, UPDATE_TIME)
VALUES ('WS006', '车间6', 12, 2, 1.0, 1, 'MVP阶段统一预设参数，后续可差异化配置', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO WW_WORKSHOP_INFO
    (WORKSHOP_ID, WORKSHOP_NAME, MAX_DISCHARGE_RATE, MIN_DISCHARGE_RATE,
     PRIORITY_WEIGHT, IS_ACTIVE, REMARK, CREATE_TIME, UPDATE_TIME)
VALUES ('WS007', '车间7', 12, 2, 1.0, 1, 'MVP阶段统一预设参数，后续可差异化配置', SYSTIMESTAMP, SYSTIMESTAMP);


COMMIT;

-- ============================================================
-- 脚本执行完毕
-- 执行结果预期：
--   5 个序列（SEQ_TANK_STATUS / SEQ_SCHEDULE_RESULT / SEQ_ALERT_LOG /
--            SEQ_SCHEDULE_INPUT / SEQ_SCHEDULE_INPUT_WORKSHOP）
--   7 张表（WW_WORKSHOP_INFO / WW_SYSTEM_CONFIG / WW_TANK_STATUS /
--           WW_SCHEDULE_RESULT / WW_ALERT_LOG /
--           WW_SCHEDULE_INPUT / WW_SCHEDULE_INPUT_WORKSHOP）
--   14 个索引
--   10 条系统参数初始数据
--   7 条车间初始数据
-- ============================================================
